// Generated by CoffeeScript 1.7.1
(function() {
  var KronicleBlog;

  KronicleBlog = (function() {
    function KronicleBlog(args) {
      new Kronicle(args);
      return;
    }

    return KronicleBlog;

  })();

  $(document).ready(function() {
    return new KronicleBlog({
      dataSources: [new ArrayDataSource()],
      routes: {
        "/": new Kronicle.View("posts"),
        "/signin": new Kronicle.View("signin"),
        "/edit": new Kronicle.View("editor")
      }
    });
  });

}).call(this);
